import { type ToolManifest, ToolRegistry } from "@nexohub/tool-sdk";

const pdfCapabilities = ["documents.read", "documents.write", "pdf.transform"] as const;

export const coreToolManifests = [
  {
    id: "pdf-organize",
    version: "1.0.0",
    name: "Organizar PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf"],
    produces: ["application/pdf"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "pdf-merge",
    version: "1.0.0",
    name: "Juntar PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf"],
    produces: ["application/pdf"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "pdf-split",
    version: "1.0.0",
    name: "Dividir PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf"],
    produces: ["application/pdf"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "pdf-rotate",
    version: "1.0.0",
    name: "Rotacionar PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf"],
    produces: ["application/pdf"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "pdf-compress",
    version: "1.0.0",
    name: "Comprimir PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf"],
    produces: ["application/pdf"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "pdf-to-word",
    version: "1.0.0",
    name: "PDF para Word",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf"],
    produces: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "word-to-pdf",
    version: "1.0.0",
    name: "Word para PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/msword",
    ],
    produces: ["application/pdf"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "images-to-pdf",
    version: "1.0.0",
    name: "Imagem para PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["image/jpeg", "image/png", "image/webp"],
    produces: ["application/pdf"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "pdf-ocr",
    version: "1.0.0",
    name: "OCR em PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf", "image/*"],
    produces: ["text/plain", "application/pdf"],
    capabilities: ["documents.read", "documents.write", "ocr.execute"],
    executor: "python",
  },
  {
    id: "pdf-protect",
    version: "1.0.0",
    name: "Proteger PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf"],
    produces: ["application/pdf"],
    capabilities: pdfCapabilities,
    executor: "native",
  },
  {
    id: "pdf-extract-images",
    version: "1.0.0",
    name: "Extrair Imagens de PDF",
    category: "pdf",
    surfaces: ["quick", "studio"],
    accepts: ["application/pdf"],
    produces: ["application/zip", "image/png"],
    capabilities: pdfCapabilities,
    executor: "python",
  },
  {
    id: "text-compare",
    version: "1.0.0",
    name: "Comparar textos",
    category: "text",
    surfaces: ["quick", "studio"],
    accepts: ["text/plain"],
    produces: ["application/vnd.nexohub.diff+json"],
    capabilities: ["documents.read", "documents.write", "text.compare"],
    executor: "browser",
  },
  {
    id: "text-review",
    version: "1.0.0",
    name: "Revisar texto",
    category: "text",
    surfaces: ["quick", "studio"],
    accepts: ["text/plain"],
    produces: ["text/plain"],
    capabilities: ["documents.read", "documents.write", "text.review"],
    executor: "native",
  },
  {
    id: "text-translate",
    version: "1.0.0",
    name: "Traduzir texto",
    category: "text",
    surfaces: ["quick", "studio"],
    accepts: ["text/plain", "text/markdown"],
    produces: ["text/plain"],
    capabilities: ["documents.read", "documents.write", "translation.execute"],
    executor: "python",
  },
] as const satisfies readonly ToolManifest[];

export function createCoreToolRegistry(): ToolRegistry {
  const registry = new ToolRegistry();
  for (const manifest of coreToolManifests) registry.register(manifest);
  return registry;
}

export const coreToolRegistry = createCoreToolRegistry();
